server:
  port: 13000

spring:
  application:
    name: queue-service

  datasource:
    url: jdbc:mysql://mysql-wallet-service.mysql-wallet-ns.svc.cluster.local:3306/wallet-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false

  cache:
    type: redis
  data:
    redis:
      host: redis-service.redis-ns.svc.cluster.local
      port: 6379
      timeout: 2000

logging:
  level:
    com.example.queueservice: DEBUG
  pattern:
    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  feign:
    client:
      config:
        default:
          loggerLevel: FULL