server:
  port: 8003

spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:mysql://mysql-reservation-service.mysql-reservation-ns.svc.cluster.local:3306/reservation-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false

  kafka:
    producer:
      bootstrap-servers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: consumerGroup
      auto-offset-reset: earliest
      bootstrap-servers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
#  tracing:
#    sampling:
#      probability: 1.0
#    propagation:
#      consume: B3
#      produce: B3
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      default-circuitbreaker:
        base-config: default

logging:
  level:
    com.example.reservationservice: DEBUG
